#!/bin/sh
echo "<!doctype html><html><head><title>Index</title><style>html{font-family:arial;}img{max-width:144px}</style><meta name='viewport' content='width=device-width, initial-scale=1.0'></head><body>" > index.html
echo "<!-- DO NOT MODIFY THIS FILE! THIS FILE WAS GENERATED BY $(basename "$(test -L "$0" && readlink "$0" || echo "$0")")! -->" >> index.html
echo "<h1>Index</h1>" >> index.html
dirArr0=(.)
while true; do
  dirArr=("${dirArr0[@]}")
  dirArr0=()
  if [ ${#dirArr[@]} -eq 0 ]; then
    break
  fi
  for x in "${dirArr[@]}"; do
    arr=($x/*)
    fileArr=()
    echo "<h2>$x</h2>" >> index.html
    for f in "${arr[@]}"; do
      if [ -d "$f" ]; then
        echo "$f is a directory";
        dirArr0+=($f)
      else
        if [ -f "$f" ]; then
          echo "$f is a file";
          if [ ${f: -4} == ".png" ]; then
            echo "<a href='$f'><img src='$f'></a>" >> index.html
          else
            fileArr+=($f)
          fi
        fi
      fi
    done
    for f in "${fileArr[@]}"; do
      echo "<a href='$f'>$f</a>" >> index.html
    done
  done
done
echo "</body></html>" >> index.html
echo "";
echo "Success!";
read -p "Press [Enter] key to continue..."
